### ISSUE TITLE
[RFE] Return the VM id from the destination provider

### ISSUE THREAD

**Issue by fdupont-redhat** [oVirt/v2v-conversion-host#23]
Today, ManageIQ looks for the VM name in the destination provider to check whether it's part of the inventory. The problem is that there may be multiple VMs with the same name, even more in Cloud providers. It would be great if virt-v2v-wrapper.py reported the VM id in the state file, so that ManageIQ could check for the unique id, composed by provider and id inside provider.

**Comment by nyoxi** [comment]
What exactly is VM id supposed to be? Is it something from VMware or ID from destination provider? If it is the first then where can one find that (I don't see any form of ID on VMware). If the second than that's problematic as such ID is known only shortly before the conversion finishes.

**Comment by fdupont-redhat** [comment]
It is the id of the VM in the destination provider. And we only need it after the conversion is finished. It will be used to check that the new VM is in the inventory after conversion. Today, we rely on the name, but it may not be unique at the provider level. So, getting it in the last update of the state file would be just fine.
