### ISSUE TITLE
nbdkit-plugin-python2 is missing.

### ISSUE THREAD

**Issue by fatihkc** [oVirt/v2v-conversion-host#76]
In install-virt-v2v.yml yum is trying to install nbdkit-plugin-python2 but it is missing. I am using Centos 8.2 with RHV installed. I don't know if it is doing something because when I changed it to the nbdkit-plugin-python3 it skips that part but still failed with VDDK. 

 ```
  "stderr": "nbdkit: error: libvixDiskLib.so.7: cannot open shared object file: No such file or directory\n\nIf 'libvixDiskLib.so.7' is located on a non-standard path you may need to\nset $LD_LIBRARY_PATH or edit /etc/ld.so.conf.\n\nSee the nbdkit-vddk-plugin(1) man page for details.",
                            "stderr_lines": [
                                "nbdkit: error: libvixDiskLib.so.7: cannot open shared object file: No such file or directory",
                                "",
                                "If 'libvixDiskLib.so.7' is located on a non-standard path you may need to",
                                "set $LD_LIBRARY_PATH or edit /etc/ld.so.conf.",
                                "",
                                "See the nbdkit-vddk-plugin(1) man page for details."
                            ],
```

My goal is live migrating VMware to RHV with ManageIQ but I cannot do it for a few weeks. I have waited for new release because I find out older version was configured for CentOS 7. I have changed my VDDK version to 6.7 but it keeps looking for 7 and can not find it.

So, should I change it to the python3 and how can I resolve this VDDK issue? Any experiences?

**Comment by nyoxi** [comment]
The project is not for live migrating VMs. The VMs will have to be shut down before migration.

It seems you have issues with EL8 host. Note that this repository is deprecated, new source is in 
[ManageIQ/manageiq-v2v-conversion_host/](https://github.com/ManageIQ/manageiq-v2v-conversion_host/tree/v1.x). Be sure to use the content from `v1.x` branch. The issues with EL8 are fixed there.
